# Generated by Django 4.2.6 on 2023-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repo', models.URLField()),
                ('jupyter_notebook', models.URLField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
