# Generated by Django 4.2.6 on 2023-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jupyter_notebook',
            field=models.URLField(blank=True),
        ),
    ]
